let appHistory = [
  {
    date: "3/14/24",
    company: "Motion Recruitment",
    positon: "Full Stack Developer",
    hiringPlatform: "LinkedIn",
    status: "Applied",
    payRange: "~$115k",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Brooksource",
    positon: "JavaScript Developer",
    hiringPlatform: "LinkedIn",
    status: "application viewed",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Pendo",
    job: "Front End Engineer: Analytics",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "$105k-$120k",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Medasource",
    job: "Frontend Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Accelerant",
    job: "Frontend Software Engineer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Staxa Technologies",
    job: "Frontend Developer",
    hiringPlatform: "Dice",
    status: "applied",
    payRange: "$40-$60/hr",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "BibleProject",
    job: "Frontend Engineer",
    hiringPlatform: "LinkedIn",
    status: "denied",
    payRange: "$90k-$114k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Rumble Advertising Center",
    job: "Front-End Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "ZapCom Group Inc",
    job: "NodeJs Developer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Gurobi Optimization",
    job: "Frontend Developer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "$80k-$169k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "ScaleIP",
    job: "Full Stack Engineer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "$135k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Brooksource",
    job: "Full Stack Engineer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "$55-$63/hr",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "NCSU",
    job: "Temporary Front End Developer",
    hiringPlatform: "Indeed",
    status: "applied",
    payRange: "$38-$42/hr",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "BetaNXT Inc",
    job: "Branding Web Designer",
    hiringPlatform: "Indeed",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Broadcom",
    job: "Senior Front-end Developer",
    hiringPlatform: "Indeed",
    status: "applied",
    payRange: "$78k-$130k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "SiriusXM",
    job: "Software Engineer III",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "$80k-$144k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "PSI (Proteam Solutions)",
    job: "Back End Developer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Kuaay",
    job: "Lead Developer",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "DTI (Diversified Technology Inc.)",
    job: "Full Stack Engineer (MERN)",
    hiringPlatform: "LinkedIn Jobs",
    status: "On Hold (2 months)",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/16/24",
    company: "TCS iBegin",
    job: "React Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/16/24",
    company: "Affirm",
    job: "Software Engineer II",
    hiringPlatform: "LinkedIn Jobs",
    status: "applied",
    payRange: "$124k-$187k",
    coldEmailed: false,
  },
  {
    date: "3/16/24",
    company: "doxo",
    job: "Front End Software Engineer",
    hiringPlatform: "LinkedIn Jobs",
    status: "denied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/17/24",
    company: "HCL Global Systems Inc",
    job: "Front End Developer",
    hiringPlatform: "Monster",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/17/24",
    company: "New Canvassing Experience",
    job: "Non-Profit Canvasser",
    hiringPlatform: "Indeed",
    status: "applied",
    payRange: "$24/hr",
    coldEmailed: false,
  },
    {
      date: "3/17/24",
      company: "Sciome",
      job: "UI/UX Developer",
      hiringPlatform: "Indeed",
      status: "applied",
      payRange: "Not Listed",
      coldEmailed: true,
    },
];

export { appHistory };
