let appHistory = [
  {
    date: "3/14/24",
    company: "Motion Recruitment",
    positon: "Full Stack Developer",
    hiringPlatform: "LinkedIn",
    status: "Applied",
    payRange: "~$115k",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Brooksource",
    positon: "JavaScript Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Pendo",
    position: "Front End Engineer: Analytics",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "$105k-$120k",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Medasource",
    position: "Frontend Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Accelerant",
    position: "Frontend Software Engineer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "Staxa Technologies",
    position: "Frontend Developer",
    hiringPlatform: "Dice",
    status: "applied",
    payRange: "$40-$60/hr",
    coldEmailed: false,
  },
  {
    date: "3/14/24",
    company: "BibleProject",
    position: "Frontend Engineer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "$90k-$114k",
    coldEmailed: false,
  },
  {
    date: "3/15/24",
    company: "Rumble Advertising Center",
    position: "Front-End Developer",
    hiringPlatform: "LinkedIn",
    status: "applied",
    payRange: "Not Listed",
    coldEmailed: false,
  },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
  //   {
  //     date: "",
  //     company: "",
  //     position: "",
  //     hiringPlatform: "",
  //     status: "",
  //     payRange: "",
  //     coldEmailed: false,
  //   },
];

export { appHistory };
